import { bot } from "../../okbot.js";
import { getUserFromMsg, isVowel, randomFromArray, sendSimpleMessage } from "../../utils.js";

export const name = "describe";
export const alias = ["desc", "slander"];
export const description = "📣 Find out what the bot perceives you as";
export const usage = "<Username OR Mention>";

const adjectives = [
	"able",
	"absolute",
	"abused",
	"abuseable",
	"acceptable",
	"actual",
	"afraid",
	"aggressive",
	"amazing",
	"ambitious",
	"angry",
	"anxious",
	"available",
	"based",
	"beautiful",
	"big",
	"blushing",
	"boring",
	"boy-liking",
	"brave",
	"caffeinated",
	"calm",
	"capable",
	"careful",
	"classic",
	"clean",
	"clumsy",
	"cold",
	"concerned",
	"confident",
	"crude",
	"crunchy",
	"crusty",
	"cuddly",
	"curious",
	"cute",
	"dangerous",
	"decent",
	"desperate",
	"different",
	"difficult",
	"dirty",
	"distinct",
	"distinguished",
	"dramatic",
	"drunk",
	"dry",
	"dumb",
	"efficient",
	"electronic",
	"embarrassed",
	"emotional",
	"enormous",
	"exciting",
	"expensive",
	"famous",
	"fantastic",
	"fast",
	"female",
	"feminine",
	"fine",
	"flat",
	"flirty",
	"fluffy",
	"free",
	"friendly",
	"gay",
	"good",
	"great",
	"guilty",
	"happy",
	"hard",
	"healthy",
	"helpful",
	"hot",
	"huge",
	"huggable",
	"hungry",
	"important",
	"impressive",
	"intelligent",
	"interesting",
	"just",
	"kissable",
	"known",
	"large",
	"leashed",
	"legal",
	"lesbian",
	"little",
	"lonely",
	"long",
	"loud",
	"loveable",
	"lovely",
	"lucky",
	"mad",
	"massive",
	"medieval",
	"mental",
	"messed up",
	"mushy",
	"nasty",
	"nefarious",
	"nervous",
	"nice",
	"obnoxious",
	"obvious",
	"odd",
	"okay",
	"old",
	"open",
	"ordinary",
	"perfect",
	"pleasant",
	"plush",
	"poor",
	"popular",
	"potential",
	"powerful",
	"practical",
	"pregnant",
	"pretty",
	"professional",
	"proper",
	"proud",
	"pure",
	"quality",
	"quick",
	"rare",
	"raw",
	"ready",
	"reasonable",
	"relevant",
	"remarkable",
	"responsible",
	"rich",
	"romantic",
	"sad",
	"scared",
	"senior",
	"sensual",
	"sentient",
	"serious",
	"severe",
	"sexual",
	"short",
	"sick",
	"significant",
	"silly",
	"sleepy",
	"slow",
	"small",
	"smart",
	"smooth",
	"sorry",
	"spiritual",
	"squishy",
	"straight",
	"strange",
	"strict",
	"strong",
	"stupid",
	"submissive",
	"successful",
	"sufficient",
	"suitable",
	"super",
	"suspicious",
	"sweet",
	"tall",
	"terminal",
	"terrible",
	"thick",
	"tight",
	"tiny",
	"traditional",
	"traumatized",
	"typical",
	"ugly",
	"undeniable",
	"unhappy",
	"unique",
	"unusual",
	"used",
	"useful",
	"usual",
	"valuable",
	"warm",
	"weak",
	"well-dressed",
	"wholesome",
	"wide",
	"willing",
	"wise",
	"wonderful",
	"young"
];
const nounsCommon = [
	"animal",
	"being",
	"boss",
	"bottom",
	"bread",
	"bum",
	"bun",
	"bunny",
	"cat",
	"chaser",
	"concept",
	"cutie",
	"daddy",
	"dog",
	"dolphin",
	"fluffer",
	"fox",
	"friend",
	"fujoshi",
	"gal",
	"girl",
	"guy",
	"individual",
	"kitsune",
	"kitten",
	"lady",
	"ladykiller",
	"lesbian",
	"maid",
	"maiden",
	"mommy",
	"monster",
	"person",
	"pet",
	"pie",
	"potato",
	"prince",
	"princess",
	"puppy",
	"queen",
	"role model",
	"shark",
	"sister",
	"slave",
	"sweetie",
	"thing",
	"top",
	"whore",
	"wife"
];
const nounsRare = [
	"baby",
	"belief",
	"chair",
	"computer",
	"disease",
	"dish",
	"dough",
	"idea",
	"kid",
	"object",
	"pastry",
	"possum",
	"priestess",
	"problem",
	"rat",
	"reality",
	"stranger",
	"subject",
	"twink",
	"vehicle",
	"villain",
	"world"
];
const endings = [
	"🤍",
	"Or so they say...",
	"Most of the time...",
	"Sometimes.",
	"Only past midnight however.",
	"It's true.",
	"We all know.",
	"It's undeniable.",
	"Teehee~",
	"Don't say otherwise.",
	"😉",
	"Just the way they should be."
];

export async function execute(msg: okbot.Message, args: string[]) {
	const usr = !args.length ? msg.author : await getUserFromMsg(msg, args);
	if (!usr) return sendSimpleMessage(msg, "User not found.");
	if (usr.id === bot.user!.id)
		return msg.reply({
			content: `\`${usr.displayName}\` is a sentient human being.`,
			allowedMentions: { repliedUser: false }
		});

	let string = "`" + usr.displayName + "` is ";
	const numAdjectives = Math.random() * 2;

	const adj1 = randomFromArray(adjectives);
	const ignoreVowel =
		adj1.startsWith("us") ||
		(adj1.startsWith("un") && adj1 !== "unusual" && adj1 !== "undeniable" && adj1 !== "unhappy");
	string += (!ignoreVowel && isVowel(adj1[0]) ? "an " : "a ") + adj1;

	if (numAdjectives > 1) {
		const separator = randomFromArray([" ", " and ", " and ", ", "]);
		const adj2 = randomFromArray(adjectives); // I guess there's a chance for drawing the same adjective twice...
		string += separator + adj2;
	}
	string += " ";

	const nounRng = Math.random();
	if (nounRng > 0.85) string += randomFromArray(nounsRare);
	else string += randomFromArray(nounsCommon);
	string += ".";

	const endingRng = Math.random();
	if (endingRng > 0.77) string += " " + randomFromArray(endings);

	msg.reply({ content: string, allowedMentions: { repliedUser: false } });
}
